<?php

/*
 * Jamal Al-Matari 2019.
 * jalmatari@gmail.com
 */

namespace Jalmatari\Http\Controllers\Admin;

use Auth;
use AutoController;
use Redirect;
use View;
use Jalmatari\Http\Controllers\Core\MyBaseController;

class MenuController extends MyBaseController
{

    public function __construct()
    {
        $this->init();
        $this->mainRoute = 'admin.menu';
    }

    public function getData($data = [])
    {
        $kind = array_search($data, [ 'site', 'admin' ]);
        //$kind = array_search($data, );
        if ($kind !== false) {
            $kind = [ 'الموقع', 'الإدارة' ][ $kind ];
            $this->customWhere = "kind='{$kind}'";
        }
        $data = [
            'icon' => [
                'icon',
                'formatter' => function ($col, $row) {
                    return "<i class='fa $col'></i> $col";
                }
            ]
        ];

        return parent::getData($data); // TODO: Change the autogenerated stub
    }

    public function fontAwesomeIcons()
    {
        return view('admin.menu.fontAwesomeIcons')->render();
    }
}
