<?php
$groups = [
    [
        'name'   => 'مدراء النظام',
        'status' => 1,
        'ord'    => 0
    ]
];


$menu = [
    [
        'parent' => 0,
        'title'  => 'لوحة التحكم',
        'name'   => 'admin2',
        'link'   => 'admin2',
        'icon'   => 'fa-tachometer',
        'ord'    => 1,
        'status' => 1
    ],
    [
        'parent' => 1,
        'title'  => 'شاشة البداية',
        'name'   => 'admin',
        'link'   => 'admin',
        'icon'   => 'fa-tachometer',
        'ord'    => 1,
        'status' => 1
    ],
    [
        'parent' => 1,
        'title'  => 'إعدادات الموقع',
        'name'   => 'settings',
        'link'   => 'admin.settings',
        'icon'   => 'fa-cogs',
        'ord'    => 2,
        'status' => 1
    ],
    [
        'parent' => 11,
        'title'  => 'بيانات الموظفين',
        'name'   => 'users',
        'link'   => 'admin.users',
        'icon'   => 'fa-user',
        'ord'    => 4,
        'status' => 1
    ],
    [
        'parent' => 11,
        'title'  => 'الوظائف والصلاحيات',
        'name'   => 'permissions',
        'link'   => 'admin.permissions',
        'icon'   => 'fa-unlock-alt',
        'ord'    => 3,
        'status' => 1
    ],
    [
        'parent' => 11,
        'title'  => 'المجموعات',
        'name'   => 'groups',
        'link'   => 'admin.groups',
        'icon'   => 'fa-users',
        'ord'    => 5,
        'status' => 1
    ],
    [
        'parent' => 10,
        'title'  => 'قوائم الموقع',
        'name'   => 'menu',
        'link'   => 'admin.menu',
        'icon'   => 'fa-indent',
        'ord'    => 7,
        'status' => 0
    ],
    [
        'parent' => 10,
        'title'  => 'الأخطاء البرمجية',
        'name'   => 'errors',
        'link'   => 'admin.errors',
        'icon'   => 'fa-warning',
        'ord'    => 6,
        'status' => 0
    ],
    [
        'parent' => 10,
        'title'  => 'جداول قاعدة البيانات',
        'name'   => 'tables',
        'link'   => 'admin.tables',
        'icon'   => 'fa-table',
        'ord'    => 8,
        'status' => 0
    ],
    [
        'parent' => 0,
        'title'  => 'خيارات النظام المتقدمة',
        'name'   => 'advanced',
        'link'   => 'advanced',
        'icon'   => 'fa-sliders',
        'ord'    => 2,
        'status' => 0
    ],
    [
        'parent' => 1,
        'title'  => 'المستخدمون والصلاحيات',
        'name'   => 'users_and_permissions',
        'link'   => 'users_and_permissions',
        'icon'   => 'fa-users',
        'ord'    => 3,
        'status' => 1
    ],
    [
        'parent' => 10,
        'title'  => 'الكونترولات',
        'name'   => 'controllers',
        'link'   => 'admin.controllers',
        'icon'   => 'fa-map-signs',
        'ord'    => 1,
        'status' => 0
    ],
    [
        'parent' => 10,
        'title'  => 'المسارات/الروابط',
        'name'   => 'routes',
        'link'   => 'admin.routes',
        'icon'   => 'fa-sitemap',
        'ord'    => 1,
        'status' => 0
    ]
];


$permissions = [
    [
        'name'                => 'User',
        'permissions'         => '[]',
        'special_permissions' => '[]',
        'ord'                 => null,
        'status'              => 1
    ],
    [
        'name'                => 'Manager',
        'permissions'         => '["admin2","admin","advanced","users_and_permissions","controllers","routes","settings","errors","menu","tables","permissions","users","groups"]',
        'special_permissions' => '["log_with_user","show_main_admin_icons"]',
        'ord'                 => 999,
        'status'              => 1
    ]
];


$settings = [
    [
        'name'    => 'settings_names',
        'desc'    => 'تسميات الإعدادات',
        'type'    => 'multi',
        'value'   => '["الإسم البرمجي للخاصية","الإسم التوضيح","النوع","القيمة","حالة العرض","القسم"]',
        'status'  => 1,
        'section' => 'main'
    ],
    [
        'name'    => 'site_title',
        'desc'    => 'عنوان الموقع',
        'type'    => 'text',
        'value'   => 'البرمجة العامة',
        'status'  => 1,
        'section' => 'main'
    ],
    [
        'name'    => 'site_meta',
        'desc'    => 'وصف الموقع',
        'type'    => 'textarea',
        'value'   => 'البرمجة العامة',
        'status'  => 1,
        'section' => 'main'
    ],
    [
        'name'    => 'tags',
        'desc'    => 'الكلمات الدليلية للموقع',
        'type'    => 'text',
        'value'   => 'البرمجة العامة',
        'status'  => 1,
        'section' => 'main'
    ],
    [
        'name'    => 'site_off',
        'desc'    => 'إغلاق الموقع',
        'type'    => 'checkbox',
        'value'   => '0',
        'status'  => 1,
        'section' => 'main'
    ],
    [
        'name'    => 'logo',
        'desc'    => 'شعار الموقع',
        'type'    => 'text',
        'value'   => '/admini/dist/img/logo.png',
        'status'  => 1,
        'section' => 'main'
    ],
    [
        'name'    => 'contact-email',
        'desc'    => 'بريد التواصل',
        'type'    => 'text',
        'value'   => 'jalmatari@gmail.com',
        'status'  => 1,
        'section' => 'main'
    ],
    [
        'name'    => 'show_errors',
        'desc'    => 'عرض الأخطاء',
        'type'    => 'checkbox',
        'value'   => '1',
        'status'  => 1,
        'section' => 'main'
    ],
    [
        'name'    => 'site_color',
        'desc'    => 'لون الموقع',
        'type'    => 'list',
        'value'   => '{"blue":"blue","purple":"purple","red":"red","yellow":"yellow","green":"green","black":"black"}',
        'status'  => 1,
        'section' => 'main'
    ],
    [
        'name'    => 'hjri_data_adjust',
        'desc'    => 'معدل تصحيح التاريخ الهجري بمقدار',
        'type'    => 'text',
        'value'   => '0',
        'status'  => 0,
        'section' => 'main'
    ],
    [
        'name'    => 'hjri_data_convert',
        'desc'    => 'تحويل التاريخ الميلادي إلى هجري',
        'type'    => 'checkbox',
        'value'   => '0',
        'status'  => 0,
        'section' => 'main'
    ],
    [
        'name'    => 'dateFormat',
        'desc'    => 'تنسيق الوقت عند العرض',
        'type'    => 'list',
        'value'   => '{"LL":"(LL) MMMM D, YYYY [January 5, 2017]","L":"(L) MM/DD/YYYY [01/05/2017]","LT":"(LT) h:mm A [5:04 PM]","LTS":"(LTS) h:mm:ss A [5:04:05 PM]","l":"(l) MM/DD/YYYY [1/5/2017]","ll":"(ll) MMMM D, YYYY [Jan 5, 2017]","LLL":"(LLL) MMMM D, YYYY h:mm A [January 5, 2017 5:04 PM]","lll":"(lll) MMMM D, YYYY h:mm A [Jan 5, 2017 5:04 PM]","LLLL":"(LLLL) dddd, MMMM D, YYYY h:mm A [Thursday, January 5, 2017 5:04 PM]","llll":"(llll) dddd, MMMM D, YYYY h:mm A [Thu, Jan 5, 2017 5:04 PM]"}',
        'status'  => 1,
        'section' => 'main'
    ]
];


$tables = [
    [
        'name'         => 'errors',
        'title'        => 'الأخطاء البرمجية',
        'new'          => 'إضافة خطأ جديد',
        'edit'         => 'تعديل خطأ',
        'status'       => 1,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'groups',
        'title'        => 'مجموعات المستخدمين',
        'new'          => 'مجموعة جديدة',
        'edit'         => 'تعديل',
        'status'       => 1,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'menu',
        'title'        => 'قوائم لوحة التحكم',
        'new'          => 'إضافة قائمة جديدة',
        'edit'         => 'تعديل قائمة',
        'status'       => 1,
        'show_add_btn' => 1,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'permissions',
        'title'        => 'صلاحيات الموظفين',
        'new'          => 'وظيفة جديدة',
        'edit'         => 'تعديل',
        'status'       => 1,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'settings',
        'title'        => 'الإعدادات',
        'new'          => 'إعداد جديد',
        'edit'         => 'تعديل إعداد',
        'status'       => 1,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'tables',
        'title'        => 'جداول قاعدة البيانات',
        'new'          => 'إضافة جدول جديد',
        'edit'         => 'تعديل جدول',
        'status'       => 1,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'tables_cols',
        'title'        => 'حقول جداول قاعدة البيانات',
        'new'          => 'إضافة حقل جديد',
        'edit'         => 'تعديل حقل',
        'status'       => 0,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'users',
        'title'        => 'بيانات الموظفين',
        'new'          => 'إضافة مستخدم جديد',
        'edit'         => 'تعديل مستخدم',
        'status'       => 1,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'users_groups',
        'title'        => 'إرتباطات المستخدمين والمجموعات',
        'new'          => 'جديد',
        'edit'         => 'تعديل',
        'status'       => 0,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'sync',
        'title'        => 'سجلات التعديلات على الجداول من أجل المزامنة',
        'new'          => 'سجل جديد',
        'edit'         => 'تعديل سجل',
        'status'       => 0,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'controllers',
        'title'        => 'الكونترولات',
        'new'          => 'إضافة جديد',
        'edit'         => 'تعديل',
        'status'       => 1,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'users_settings',
        'title'        => 'إعدادات المستخدمين',
        'new'          => 'جديد',
        'edit'         => 'تعديل',
        'status'       => 0,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'routes',
        'title'        => 'المسارات/الروابط',
        'new'          => 'إضافة جديد',
        'edit'         => 'تعديل',
        'status'       => 1,
        'show_add_btn' => 1,
        'namespace'    => 'Jalmatari\\Models\\'
    ]
];


$tables_cols = [
    [
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(10) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'رقم الخطأ',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 1
    ],
    [
        'COLUMN_NAME'      => 'user_id',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'رقم المستخدم',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 1
    ],
    [
        'COLUMN_NAME'      => 'request',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'mediumtext',
        'COLUMN_TYPE'      => 'mediumtext',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الطلب',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 1
    ],
    [
        'COLUMN_NAME'      => 'rendered_page',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'mediumtext',
        'COLUMN_TYPE'      => 'mediumtext',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'صفحة الخطأ',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 1
    ],
    [
        'COLUMN_NAME'      => 'exception',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'mediumtext',
        'COLUMN_TYPE'      => 'mediumtext',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الخطأ',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 1
    ],
    [
        'COLUMN_NAME'      => 'exception_name',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(255)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'اسم الخطأ',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 1
    ],
    [
        'COLUMN_NAME'      => 'url',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(255)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الرابط',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 1
    ],
    [
        'COLUMN_NAME'      => 'exception_msg',
        'ORDINAL_POSITION' => 8,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'text',
        'COLUMN_TYPE'      => 'text',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'رسالة الخطأ',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 1
    ],
    [
        'COLUMN_NAME'      => 'status',
        'ORDINAL_POSITION' => 9,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'حالة الإطلاع',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 1
    ],
    [
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 10,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ الخطأ',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 1
    ],
    [
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 11,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ التعديل',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 1
    ],
    [
        'COLUMN_NAME'      => 'name',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(200)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'اسم المجموعة',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 2
    ],
    [
        'COLUMN_NAME'      => 'status',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'حالة التفعيل',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 2
    ],
    [
        'COLUMN_NAME'      => 'ord',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(2)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 2
    ],
    [
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ الإنشاء',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 2
    ],
    [
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ التعديل',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 2
    ],
    [
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 2
    ],
    [
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(2)',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 3
    ],
    [
        'COLUMN_NAME'      => 'parent',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(2)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'القائمة الأب',
        'TYPE'             => 2,
        'SOURCE'           => '{"function":"GetMenuParents"}',
        'ATTR'             => '{"class":"required"}',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 3
    ],
    [
        'COLUMN_NAME'      => 'title',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(255)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'عنوان القائمة',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 3
    ],
    [
        'COLUMN_NAME'      => 'name',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(255)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الإسم البرمجي',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 3
    ],
    [
        'COLUMN_NAME'      => 'link',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(255)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'رابط القائمة',
        'TYPE'             => 2,
        'SOURCE'           => '{"function":"RoutesNamesList"}',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 3
    ],
    [
        'COLUMN_NAME'      => 'icon',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(255)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الأيقونة',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 3
    ],
    [
        'COLUMN_NAME'      => 'ord',
        'ORDINAL_POSITION' => 10,
        'COLUMN_DEFAULT'   => '1',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(2)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الترتيب',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 3
    ],
    [
        'COLUMN_NAME'      => 'status',
        'ORDINAL_POSITION' => 11,
        'COLUMN_DEFAULT'   => '1',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'حالة النشر',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 3
    ],
    [
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 4
    ],
    [
        'COLUMN_NAME'      => 'name',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(200)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'المسمى الوظيفي',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 4
    ],
    [
        'COLUMN_NAME'      => 'permissions',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(2000)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الصلاحيات',
        'TYPE'             => 8,
        'SOURCE'           => '',
        'ATTR'             => '{"class":"fun_get_permissions_fileds"}',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 4
    ],
    [
        'COLUMN_NAME'      => 'special_permissions',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(2000)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'صلاحيات خاصة',
        'TYPE'             => 8,
        'SOURCE'           => '',
        'ATTR'             => '{"class":"fun_get_special_permissions_fileds"}',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 4
    ],
    [
        'COLUMN_NAME'      => 'ord',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(2)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 4
    ],
    [
        'COLUMN_NAME'      => 'status',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'حالة التفعيل',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 4
    ],
    [
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ الإنشاء',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 4
    ],
    [
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 8,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ التعديل',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 4
    ],
    [
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '#',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 5
    ],
    [
        'COLUMN_NAME'      => 'name',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(200)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الاسم البرمجي للإعداد',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 5
    ],
    [
        'COLUMN_NAME'      => 'desc',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(200)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تسمية/وصف الإعداد',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 5
    ],
    [
        'COLUMN_NAME'      => 'type',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => '"text"',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'enum',
        'COLUMN_TYPE'      => 'enum("text","checkbox","textarea","multi","editor","article","list","multi_list","hidden")',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'نوع حقل الإعداد',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 5
    ],
    [
        'COLUMN_NAME'      => 'value',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'text',
        'COLUMN_TYPE'      => 'text',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'قيمة الإعداد',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 5
    ],
    [
        'COLUMN_NAME'      => 'status',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => '1',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'حالة النشر',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 5
    ],
    [
        'COLUMN_NAME'      => 'section',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => '"site"',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(20)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تصنيف الإعداد',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 5
    ],
    [
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(10) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 6
    ],
    [
        'COLUMN_NAME'      => 'name',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(500)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'اسم الجدول',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 6
    ],
    [
        'COLUMN_NAME'      => 'title',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(500)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'عنوان الصفحة المرتبطة بالجدول',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 6
    ],
    [
        'COLUMN_NAME'      => 'new',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => '"جديد"',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(500)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'عنوان زر إضافة جديد',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 6
    ],
    [
        'COLUMN_NAME'      => 'edit',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => '"تعديل"',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(500)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'عنوان زر تعديل',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 6
    ],
    [
        'COLUMN_NAME'      => 'status',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'عرض كقائمة',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 6
    ],
    [
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 8,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ الإنشاء',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 6
    ],
    [
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 9,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ التعديل',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 6
    ],
    [
        'COLUMN_NAME'      => 'show_add_btn',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'إظهار زر إضافة جديد',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 6
    ],
    [
        'COLUMN_NAME'      => 'namespace',
        'ORDINAL_POSITION' => 8,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(500)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'المسار البرمجي للموديل',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 6
    ],
    [
        'COLUMN_NAME'      => 'ID',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(10) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'COLUMN_NAME'      => 'COLUMN_NAME',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(64)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'اسم الحقل',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'COLUMN_NAME'      => 'ORDINAL_POSITION',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(10)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الترتيب',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'COLUMN_NAME'      => 'COLUMN_DEFAULT',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'longtext',
        'COLUMN_TYPE'      => 'longtext',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'القيمة الإفتراضية للحقل',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'COLUMN_NAME'      => 'IS_NULLABLE',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(3)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'هل الحقل يقبل القيمة NULL',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'COLUMN_NAME'      => 'DATA_TYPE',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(64)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'نوع الحقل في قاعدة البيانات',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'COLUMN_NAME'      => 'COLUMN_TYPE',
        'ORDINAL_POSITION' => 8,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'longtext',
        'COLUMN_TYPE'      => 'longtext',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'نوع الحقل في قاعدة البيانات',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'COLUMN_NAME'      => 'EXTRA',
        'ORDINAL_POSITION' => 9,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الخصائص الإضافية للحقل',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'COLUMN_NAME'      => 'COLUMN_COMMENT',
        'ORDINAL_POSITION' => 0,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(1024)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الترتيب',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'COLUMN_NAME'      => 'TITLE',
        'ORDINAL_POSITION' => 11,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(500)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'عنوان الحقل بالعربي',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'COLUMN_NAME'      => 'TYPE',
        'ORDINAL_POSITION' => 12,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(2)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'نوع الحقل عند التحرير',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'COLUMN_NAME'      => 'SOURCE',
        'ORDINAL_POSITION' => 13,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(1024)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'مصدر بيانات الحقل',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'COLUMN_NAME'      => 'ATTR',
        'ORDINAL_POSITION' => 14,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(1024)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'خصائص الحقل',
        'TYPE'             => 1,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'COLUMN_NAME'      => 'STATUS',
        'ORDINAL_POSITION' => 15,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'نشر',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'COLUMN_NAME'      => 'SHOW_IN_LIST',
        'ORDINAL_POSITION' => 16,
        'COLUMN_DEFAULT'   => '1',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'عرض الحقل كعمود في صفحة العرض',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 17,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ الإنشاء',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 18,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ التعديل',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'COLUMN_NAME'      => 'TABLE_ID',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(10)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الجدول',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'COLUMN_NAME'      => 'api_token',
        'ORDINAL_POSITION' => 15,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(60)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'COLUMN_NAME'      => 'created_by_app',
        'ORDINAL_POSITION' => 16,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تم إنشاء المستخدم بواسطة التطبيق',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 8
    ],
    [
        'COLUMN_NAME'      => 'name',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'اسم الموظف',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 8
    ],
    [
        'COLUMN_NAME'      => 'username',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(20)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'اسم المستخدم',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'COLUMN_NAME'      => 'password',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(60)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'كلمة المرور',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'COLUMN_NAME'      => 'phone',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(20)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'رقم الجوال',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'COLUMN_NAME'      => 'email',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(50)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'البريد الإلكتروني',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'COLUMN_NAME'      => 'photo',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الصورة الشخصية',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '{"id":"img-upload"}',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'COLUMN_NAME'      => 'job_title',
        'ORDINAL_POSITION' => 8,
        'COLUMN_DEFAULT'   => '1',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(3)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'المسمى الوظيفي',
        'TYPE'             => 2,
        'SOURCE'           => '{"function":"GetUserJobs"}',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 8
    ],
    [
        'COLUMN_NAME'      => 'status',
        'ORDINAL_POSITION' => 9,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'حالة التفعيل',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 8
    ],
    [
        'COLUMN_NAME'      => 'permissions',
        'ORDINAL_POSITION' => 10,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(2000)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'صلاحيات إضافية',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'COLUMN_NAME'      => 'remember_token',
        'ORDINAL_POSITION' => 11,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(60)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 12,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'آخر دخول',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 13,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ الإنشاء',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 8
    ],
    [
        'COLUMN_NAME'      => 'email_verified_at',
        'ORDINAL_POSITION' => 14,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تفعيل البريد',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'COLUMN_NAME'      => 'city',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(50)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'المدينة',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'COLUMN_NAME'      => 'country',
        'ORDINAL_POSITION' => 8,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(50)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الدولة',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 9
    ],
    [
        'COLUMN_NAME'      => 'user_id',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 9
    ],
    [
        'COLUMN_NAME'      => 'group_id',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 9
    ],
    [
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ الإنشاء',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 9
    ],
    [
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ التعديل',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 9
    ],
    [
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11)',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 10
    ],
    [
        'COLUMN_NAME'      => 'table',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'text',
        'COLUMN_TYPE'      => 'text',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'اسم الجدول',
        'TYPE'             => 5,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 10
    ],
    [
        'COLUMN_NAME'      => 'row_id',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'رقم السجل/الصف',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 10
    ],
    [
        'COLUMN_NAME'      => 'action',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'العملية',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 10
    ],
    [
        'COLUMN_NAME'      => 'user_id',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'المستخدم',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 10
    ],
    [
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ التحديث',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 10
    ],
    [
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ العملية',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 10
    ],
    [
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(10) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 11
    ],
    [
        'COLUMN_NAME'      => 'name',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'اسم الكونترولر',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 11
    ],
    [
        'COLUMN_NAME'      => 'title',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'عنوان الكونترولر',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 11
    ],
    [
        'COLUMN_NAME'      => 'namespace',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => '"تعديل"',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'المجلد/مساحة الاسم البرمجي',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 11
    ],
    [
        'COLUMN_NAME'      => 'url_prefix',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => '"تعديل"',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'لاحقة الروابط المرتبطة بالكونترولر',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 11
    ],
    [
        'COLUMN_NAME'      => 'table_id',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(10)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الجدول المرتبط بالكنترولر',
        'TYPE'             => 2,
        'SOURCE'           => '{"function":"TablesList"}',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 11
    ],
    [
        'COLUMN_NAME'      => 'status',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الروابط الأساسية*',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 11
    ],
    [
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 8,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ الإنشاء',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 11
    ],
    [
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 9,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ التعديل',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 11
    ],
    [
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11)',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '#',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 12
    ],
    [
        'COLUMN_NAME'      => 'user_id',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'رقم الموظف',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 12
    ],
    [
        'COLUMN_NAME'      => 'setting',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الإعداد',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 12
    ],
    [
        'COLUMN_NAME'      => 'value',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'القيمة',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 12
    ],
    [
        'COLUMN_NAME'      => 'value2',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'قميمة٢',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 12
    ],
    [
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ التعديل',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 12
    ],
    [
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ الإنشاء',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 12
    ],
    [
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(10) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 13
    ],
    [
        'COLUMN_NAME'      => 'type',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'نوع الرابط',
        'TYPE'             => 2,
        'SOURCE'           => '{"function":"RoutesTypesList"}',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 13
    ],
    [
        'COLUMN_NAME'      => 'middleware',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(10)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'المصادقة',
        'TYPE'             => 2,
        'SOURCE'           => '{"function":"MiddlewareList"}',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 13
    ],
    [
        'COLUMN_NAME'      => 'controller_id',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(10)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الكنترولر',
        'TYPE'             => 2,
        'SOURCE'           => '{"function":"ControllersList"}',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 13
    ],
    [
        'COLUMN_NAME'      => 'action',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(50)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الدالة للتنفيذ',
        'TYPE'             => 2,
        'SOURCE'           => '{"function":"ControllersActionsList"}',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 13
    ],
    [
        'COLUMN_NAME'      => 'route',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'الرابط',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 13
    ],
    [
        'COLUMN_NAME'      => 'id_required',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'يتطلب رقم id',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 13
    ],
    [
        'COLUMN_NAME'      => 'status',
        'ORDINAL_POSITION' => 8,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'نشر',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 13
    ],
    [
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 9,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ الإنشاء',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 13
    ],
    [
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 10,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => 'تاريخ التعديل',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 13
    ]
];


$users = [
    [
        'api_token'         => 'zI1UE9EhcuqvCt3HKpBSjLiIMuxGHAU0OpTjvEsw3xL5YB6YwQYSL85Fjk35',
        'created_by_app'    => 0,
        'name'              => 'مدير النظام',
        'username'          => 'مدير النظام',
        'password'          => '$2y$10$qwOQ.DAWY2NPJNtc9biFZubktOtHB6Mr7NMxil2ZhrtBz4gcTabF.',
        'phone'             => '00967777523272',
        'email'             => 'jalmatari@gmail.com',
        'photo'             => '/jalmatari/img/users/u_1_user6-128x128-1.jpg',
        'job_title'         => 2,
        'status'            => 1,
        'permissions'       => '[]',
        'remember_token'    => 'QX5LUOOTkaDhsCYVi1NrlvMgGvvSp3HylLAMVD77idjQUCYpor4IElDQeqj1',
        'email_verified_at' => null,
        'city'              => 'الرياض',
        'country'           => 'السعودية'
    ]
];


$users_groups = [
    [
        'user_id'  => 1,
        'group_id' => 1
    ]
];


$controllers = [
    [
        'name'       => 'AdminController',
        'title'      => '',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Admin',
        'url_prefix' => '',
        'table_id'   => 0,
        'status'     => 0
    ],
    [
        'name'       => 'ControllersController',
        'title'      => 'الكونترولات',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Admin',
        'url_prefix' => 'controllers',
        'table_id'   => 11,
        'status'     => 1
    ],
    [
        'name'       => 'GroupsController',
        'title'      => 'مجموعات المستخدمين',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Admin',
        'url_prefix' => 'groups',
        'table_id'   => 2,
        'status'     => 1
    ],
    [
        'name'       => 'MenuController',
        'title'      => 'قوائم لوحة التحكم',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Admin',
        'url_prefix' => 'menu',
        'table_id'   => 3,
        'status'     => 1
    ],
    [
        'name'       => 'PermissionsController',
        'title'      => 'صلاحيات الموظفين',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Admin',
        'url_prefix' => 'permissions',
        'table_id'   => 4,
        'status'     => 1
    ],
    [
        'name'       => 'SettingsController',
        'title'      => 'الإعدادات',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Admin',
        'url_prefix' => 'settings',
        'table_id'   => 5,
        'status'     => 1
    ],
    [
        'name'       => 'TablesController',
        'title'      => 'جداول قاعدة البيانات',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Admin',
        'url_prefix' => 'tables',
        'table_id'   => 6,
        'status'     => 1
    ],
    [
        'name'       => 'UsersController',
        'title'      => 'بيانات الموظفين',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Admin',
        'url_prefix' => 'users',
        'table_id'   => 8,
        'status'     => 1
    ],
    [
        'name'       => 'APIController',
        'title'      => '',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Core',
        'url_prefix' => '',
        'table_id'   => 0,
        'status'     => 0
    ],
    [
        'name'       => 'AppController',
        'title'      => '',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Core',
        'url_prefix' => '',
        'table_id'   => 0,
        'status'     => 0
    ],
    [
        'name'       => 'ErrorsController',
        'title'      => 'الأخطاء البرمجية',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Core',
        'url_prefix' => 'errors',
        'table_id'   => 1,
        'status'     => 1
    ],
    [
        'name'       => 'RoutesController',
        'title'      => 'الروابط',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Admin',
        'url_prefix' => 'routes',
        'table_id'   => 13,
        'status'     => 1
    ]
];


$routes = [
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 7,
        'action'        => 'recheck',
        'route'         => 'recheck',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 7,
        'action'        => 'route',
        'route'         => 'route',
        'id_required'   => 1,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 7,
        'action'        => 'cols',
        'route'         => 'cols',
        'id_required'   => 1,
        'status'        => 1
    ],
    [
        'type'          => 1,
        'middleware'    => 'AdminAuth',
        'controller_id' => 7,
        'action'        => 'saveCols',
        'route'         => 'cols',
        'id_required'   => 1,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 7,
        'action'        => 'genController',
        'route'         => 'genController',
        'id_required'   => 1,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 7,
        'action'        => 'genMolel',
        'route'         => 'genMolel',
        'id_required'   => 1,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 7,
        'action'        => 'addTablesToMenus',
        'route'         => 'addTablesToMenus',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 8,
        'action'        => 'login_as',
        'route'         => 'login_as',
        'id_required'   => 1,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 1,
        'action'        => 'index',
        'route'         => 'admin',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 1,
        'action'        => 'index',
        'route'         => 'start',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 11,
        'action'        => 'error',
        'route'         => 'error',
        'id_required'   => 1,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 11,
        'action'        => 'delete_all',
        'route'         => 'delete_all',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 1,
        'action'        => 'unauthorized',
        'route'         => 'unauthorized',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 1,
        'action'        => 'construction',
        'route'         => 'construction',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'PublicAuth',
        'controller_id' => 1,
        'action'        => 'createSession',
        'route'         => 'admin.login',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 1,
        'action'        => 'destroySession',
        'route'         => 'admin.logout',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 1,
        'middleware'    => 'PublicAuth',
        'controller_id' => 1,
        'action'        => 'storeSession',
        'route'         => 'admin.login',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 2,
        'action'        => 'reCheck',
        'route'         => 'reCheck',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'PublicAuth',
        'controller_id' => 1,
        'action'        => 'clearCache',
        'route'         => 'clearCache',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'PublicAuth',
        'controller_id' => 10,
        'action'        => 'api',
        'route'         => 'app.api',
        'id_required'   => 0,
        'status'        => 1
    ]
];


return [
    'groups'       => $groups,
    'menu'         => $menu,
    'permissions'  => $permissions,
    'settings'     => $settings,
    'tables'       => $tables,
    'tables_cols'  => $tables_cols,
    'users'        => $users,
    'users_groups' => $users_groups,
    'controllers'  => $controllers,
    'routes'       => $routes,
];


