<?php
$groups = [[
        'name'   => 'مدراء النظام',
        'status' => 1,
        'ord'    => 0
    ]];


$menu = [[
        'parent' => 0,
        'title'  => 'لوحة التحكم',
        'name'   => 'admin2',
        'link'   => 'admin2',
        'icon'   => 'fa-tachometer',
        'ord'    => 1,
        'status' => 1
    ],
    [
        'parent' => 1,
        'title'  => 'شاشة البداية',
        'name'   => 'admin',
        'link'   => 'admin',
        'icon'   => 'fa-tachometer',
        'ord'    => 1,
        'status' => 1
    ],
    [
        'parent' => 1,
        'title'  => 'إعدادات الموقع',
        'name'   => 'settings',
        'link'   => 'admin.settings',
        'icon'   => 'fa-cogs',
        'ord'    => 2,
        'status' => 1
    ],
    [
        'parent' => 11,
        'title'  => 'بيانات الموظفين',
        'name'   => 'users',
        'link'   => 'admin.users',
        'icon'   => 'fa-user',
        'ord'    => 4,
        'status' => 1
    ],
    [
        'parent' => 11,
        'title'  => 'الوظائف والصلاحيات',
        'name'   => 'permissions',
        'link'   => 'admin.permissions',
        'icon'   => 'fa-unlock-alt',
        'ord'    => 3,
        'status' => 1
    ],
    [
        'parent' => 11,
        'title'  => 'المجموعات',
        'name'   => 'groups',
        'link'   => 'admin.groups',
        'icon'   => 'fa-users',
        'ord'    => 5,
        'status' => 1
    ],
    [
        'parent' => 10,
        'title'  => 'قوائم الموقع',
        'name'   => 'menu',
        'link'   => 'admin.menu',
        'icon'   => 'fa-indent',
        'ord'    => 7,
        'status' => 0
    ],
    [
        'parent' => 10,
        'title'  => 'الأخطاء البرمجية',
        'name'   => 'errors',
        'link'   => 'admin.errors',
        'icon'   => 'fa-warning',
        'ord'    => 6,
        'status' => 0
    ],
    [
        'parent' => 10,
        'title'  => 'جداول قاعدة البيانات',
        'name'   => 'tables',
        'link'   => 'admin.tables',
        'icon'   => 'fa-table',
        'ord'    => 8,
        'status' => 0
    ],
    [
        'parent' => 0,
        'title'  => 'خيارات النظام المتقدمة',
        'name'   => 'advanced',
        'link'   => 'advanced',
        'icon'   => 'fa-sliders',
        'ord'    => 2,
        'status' => 0
    ],
    [
        'parent' => 1,
        'title'  => 'المستخدمون والصلاحيات',
        'name'   => 'users_and_permissions',
        'link'   => 'users_and_permissions',
        'icon'   => 'fa-users',
        'ord'    => 3,
        'status' => 1
    ],
    [
        'parent' => 10,
        'title'  => 'الكونترولات',
        'name'   => 'controllers',
        'link'   => 'admin.controllers',
        'icon'   => 'fa-map-signs',
        'ord'    => 1,
        'status' => 0
    ],
    [
        'parent' => 10,
        'title'  => 'المسارات\/الروابط',
        'name'   => 'routes',
        'link'   => 'admin.routes',
        'icon'   => 'fa-sitemap',
        'ord'    => 1,
        'status' => 0
    ]];


$permissions = [[
        'name'                => 'User',
        'permissions'         => '[]',
        'special_permissions' => '[]',
        'ord'                 => null,
        'status'              => 1
    ],
    [
        'name'                => 'Manager',
        'permissions'         => '[\'admin2\',\'admin\',\'advanced\',\'users_and_permissions\',\'controllers\',\'routes\',\'settings\',\'errors\',\'menu\',\'tables\',\'permissions\',\'users\',\'groups\']',
        'special_permissions' => '[\'log_with_user\',\'show_main_admin_icons\']',
        'ord'                 => 999,
        'status'              => 1
    ]];


$settings = [[
        'name'    => 'settings_names',
        'desc'    => 'تسميات الإعدادات',
        'type'    => 'multi',
        'value'   => '[\'الإسم البرمجي للخاصية\',\'الإسم التوضيح\',\'النوع\',\'القيمة\',\'حالة العرض\',\'القسم\']',
        'status'  => 1,
        'section' => 'main'
    ],
    [
        'name'    => 'site_title',
        'desc'    => 'عنوان الموقع',
        'type'    => 'text',
        'value'   => 'البرمجة العامة',
        'status'  => 1,
        'section' => 'main'
    ],
    [
        'name'    => 'site_meta',
        'desc'    => 'وصف الموقع',
        'type'    => 'textarea',
        'value'   => 'البرمجة العامة',
        'status'  => 1,
        'section' => 'main'
    ],
    [
        'name'    => 'tags',
        'desc'    => 'الكلمات الدليلية للموقع',
        'type'    => 'text',
        'value'   => 'البرمجة العامة',
        'status'  => 1,
        'section' => 'main'
    ],
    [
        'name'    => 'site_off',
        'desc'    => 'إغلاق الموقع',
        'type'    => 'checkbox',
        'value'   => '0',
        'status'  => 1,
        'section' => 'main'
    ],
    [
        'name'    => 'logo',
        'desc'    => 'شعار الموقع',
        'type'    => 'text',
        'value'   => '\/admini\/dist\/img\/logo.png',
        'status'  => 1,
        'section' => 'main'
    ],
    [
        'name'    => 'contact-email',
        'desc'    => 'بريد التواصل',
        'type'    => 'text',
        'value'   => 'jalmatari@gmail.com',
        'status'  => 1,
        'section' => 'main'
    ],
    [
        'name'    => 'show_errors',
        'desc'    => 'عرض الأخطاء',
        'type'    => 'checkbox',
        'value'   => '1',
        'status'  => 1,
        'section' => 'main'
    ],
    [
        'name'    => 'site_color',
        'desc'    => 'لون الموقع',
        'type'    => 'list',
        'value'   => '[\'blue\'=>\'blue\',\'purple\'=>\'purple\',\'red\'=>\'red\',\'yellow\'=>\'yellow\',\'green\'=>\'green\',\'black\'=>\'black\']',
        'status'  => 1,
        'section' => 'main'
    ],
    [
        'name'    => 'hjri_data_adjust',
        'desc'    => 'معدل تصحيح التاريخ الهجري بمقدار',
        'type'    => 'text',
        'value'   => '0',
        'status'  => 0,
        'section' => 'main'
    ],
    [
        'name'    => 'hjri_data_convert',
        'desc'    => 'تحويل التاريخ الميلادي إلى هجري',
        'type'    => 'checkbox',
        'value'   => '0',
        'status'  => 0,
        'section' => 'main'
    ]];


$tables = [[
        'name'         => 'errors',
        'title'        => 'الأخطأ البرمجية',
        'new'          => 'إضافة خطأ جديد',
        'edit'         => 'تعديل خطأ',
        'status'       => 1,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'groups',
        'title'        => 'مجموعات المستخدمين',
        'new'          => 'مجموعة جديدة',
        'edit'         => 'تعديل',
        'status'       => 1,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'menu',
        'title'        => 'قوائم لوحة التحكم',
        'new'          => 'إضافة قائمة جديدة',
        'edit'         => 'تعديل قائمة',
        'status'       => 1,
        'show_add_btn' => 1,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'permissions',
        'title'        => 'صلاحيات الموظفين',
        'new'          => 'وظيفة جديدة',
        'edit'         => 'تعديل',
        'status'       => 1,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'settings',
        'title'        => 'الإعدادات',
        'new'          => 'إعداد جديد',
        'edit'         => 'تعديل إعداد',
        'status'       => 1,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'tables',
        'title'        => 'جداول قاعدة البيانات',
        'new'          => 'إضافة جدول جديد',
        'edit'         => 'تعديل جدول',
        'status'       => 1,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'tables_cols',
        'title'        => 'حقول جداول قاعدة البيانات',
        'new'          => 'إضافة حقل جديد',
        'edit'         => 'تعديل حقل',
        'status'       => 0,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'users',
        'title'        => 'بيانات الموظفين',
        'new'          => 'إضافة مستخدم جديد',
        'edit'         => 'تعديل مستخدم',
        'status'       => 1,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'users_groups',
        'title'        => 'إرتباطات المستخدمين والمجموعات',
        'new'          => 'جديد',
        'edit'         => 'تعديل',
        'status'       => 0,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'sync',
        'title'        => 'سجلات التعديلات على الجداول من أجل المزامنة',
        'new'          => 'سجل جديد',
        'edit'         => 'تعديل سجل',
        'status'       => 0,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'controllers',
        'title'        => 'الكونترولات',
        'new'          => 'إضافة جديد',
        'edit'         => 'تعديل',
        'status'       => 1,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'users_settings',
        'title'        => 'إعدادات المستخدمين',
        'new'          => 'جديد',
        'edit'         => 'تعديل',
        'status'       => 0,
        'show_add_btn' => 0,
        'namespace'    => 'Jalmatari\\Models\\'
    ],
    [
        'name'         => 'routes',
        'title'        => 'المسارات\/الروابط',
        'new'          => 'إضافة جديد',
        'edit'         => 'تعديل',
        'status'       => 1,
        'show_add_btn' => 1,
        'namespace'    => 'Jalmatari\\Models\\'
    ]];


$tables_cols = [[
        'ID'               => 1,
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(10) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '[\'title\'=>\'رقم الخطأ\',\'type\'=>\'0\']',
        'TITLE'            => 'رقم الخطأ',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 1
    ],
    [
        'ID'               => 2,
        'COLUMN_NAME'      => 'user_id',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'رقم المستخدم\',\'type\'=>\'0\']',
        'TITLE'            => 'رقم المستخدم',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 1
    ],
    [
        'ID'               => 3,
        'COLUMN_NAME'      => 'request',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'mediumtext',
        'COLUMN_TYPE'      => 'mediumtext',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الطلب\',\'type\'=>\'0\']',
        'TITLE'            => 'الطلب',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 1
    ],
    [
        'ID'               => 4,
        'COLUMN_NAME'      => 'rendered_page',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'mediumtext',
        'COLUMN_TYPE'      => 'mediumtext',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'صفحة الخطأ\',\'type\'=>\'0\']',
        'TITLE'            => 'صفحة الخطأ',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 1
    ],
    [
        'ID'               => 5,
        'COLUMN_NAME'      => 'exception',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'mediumtext',
        'COLUMN_TYPE'      => 'mediumtext',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الخطأ\',\'type\'=>\'0\']',
        'TITLE'            => 'الخطأ',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 1
    ],
    [
        'ID'               => 6,
        'COLUMN_NAME'      => 'exception_name',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(255)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'اسم الخطأ\',\'type\'=>\'0\']',
        'TITLE'            => 'اسم الخطأ',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 1
    ],
    [
        'ID'               => 7,
        'COLUMN_NAME'      => 'url',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(255)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الرابط\',\'type\'=>\'0\']',
        'TITLE'            => 'الرابط',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 1
    ],
    [
        'ID'               => 8,
        'COLUMN_NAME'      => 'exception_msg',
        'ORDINAL_POSITION' => 8,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'text',
        'COLUMN_TYPE'      => 'text',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'رسالة الخطأ\',\'type\'=>\'0\']',
        'TITLE'            => 'رسالة الخطأ',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 1
    ],
    [
        'ID'               => 9,
        'COLUMN_NAME'      => 'status',
        'ORDINAL_POSITION' => 9,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'حالة الإطلاع\',\'type\'=>\'3\']',
        'TITLE'            => 'حالة الإطلاع',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 1
    ],
    [
        'ID'               => 10,
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 10,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ الخطأ\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ الخطأ',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 1
    ],
    [
        'ID'               => 11,
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 11,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ التعديل\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ التعديل',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 1
    ],
    [
        'ID'               => 12,
        'COLUMN_NAME'      => 'name',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(200)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'اسم المجموعة\',\'type\'=>\'0\']',
        'TITLE'            => 'اسم المجموعة',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 2
    ],
    [
        'ID'               => 13,
        'COLUMN_NAME'      => 'status',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'حالة التفعيل\',\'type\'=>\'3\']',
        'TITLE'            => 'حالة التفعيل',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 2
    ],
    [
        'ID'               => 14,
        'COLUMN_NAME'      => 'ord',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(2)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'#\',\'type\'=>\'4\']',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 2
    ],
    [
        'ID'               => 15,
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ الإنشاء\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ الإنشاء',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 2
    ],
    [
        'ID'               => 16,
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ التعديل\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ التعديل',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 2
    ],
    [
        'ID'               => 17,
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '[\'title\'=>\'#\',\'type\'=>\'4\']',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 2
    ],
    [
        'ID'               => 18,
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(2)',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '[\'title\'=>\'#\',\'type\'=>\'4\']',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 3
    ],
    [
        'ID'               => 19,
        'COLUMN_NAME'      => 'parent',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(2)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'القائمة الأب\',\'type\'=>\'2\',\'para\'=>[\'class\'=>\'required\',\'source\'=>[\'function\'=>\'GetMenuParents\']]]',
        'TITLE'            => 'القائمة الأب',
        'TYPE'             => 2,
        'SOURCE'           => '[\'function\'=>\'GetMenuParents\']',
        'ATTR'             => '[\'class\'=>\'required\']',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 3
    ],
    [
        'ID'               => 20,
        'COLUMN_NAME'      => 'title',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(255)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'عنوان القائمة\',\'type\'=>\'0\']',
        'TITLE'            => 'عنوان القائمة',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 3
    ],
    [
        'ID'               => 21,
        'COLUMN_NAME'      => 'name',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(255)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الإسم البرمجي\',\'type\'=>\'0\']',
        'TITLE'            => 'الإسم البرمجي',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 3
    ],
    [
        'ID'               => 22,
        'COLUMN_NAME'      => 'link',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(255)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'رابط القائمة\',\'type\'=>\'2\',\'para\'=>[\'source\'=>[\'function\'=>\'RoutesNamesList\']]]',
        'TITLE'            => 'رابط القائمة',
        'TYPE'             => 2,
        'SOURCE'           => '[\'function\'=>\'RoutesNamesList\']',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 3
    ],
    [
        'ID'               => 23,
        'COLUMN_NAME'      => 'icon',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(255)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الأيقونة\',\'type\'=>\'0\']',
        'TITLE'            => 'الأيقونة',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 3
    ],
    [
        'ID'               => 24,
        'COLUMN_NAME'      => 'ord',
        'ORDINAL_POSITION' => 10,
        'COLUMN_DEFAULT'   => '1',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(2)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الترتيب\',\'type\'=>\'0\']',
        'TITLE'            => 'الترتيب',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 3
    ],
    [
        'ID'               => 25,
        'COLUMN_NAME'      => 'status',
        'ORDINAL_POSITION' => 11,
        'COLUMN_DEFAULT'   => '1',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'حالة النشر\',\'type\'=>\'3\']',
        'TITLE'            => 'حالة النشر',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 3
    ],
    [
        'ID'               => 26,
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '[\'title\'=>\'#\',\'type\'=>\'4\']',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 4
    ],
    [
        'ID'               => 27,
        'COLUMN_NAME'      => 'name',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(200)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'المسمى الوظيفي\',\'type\'=>\'0\']',
        'TITLE'            => 'المسمى الوظيفي',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 4
    ],
    [
        'ID'               => 28,
        'COLUMN_NAME'      => 'permissions',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(2000)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الصلاحيات\',\'type\'=>\'8\',\'para\'=>[\'class\'=>\'fun_get_permissions_fileds\']]',
        'TITLE'            => 'الصلاحيات',
        'TYPE'             => 8,
        'SOURCE'           => '',
        'ATTR'             => '[\'class\'=>\'fun_get_permissions_fileds\']',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 4
    ],
    [
        'ID'               => 29,
        'COLUMN_NAME'      => 'special_permissions',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(2000)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'صلاحيات خاصة\',\'type\'=>\'8\',\'para\'=>[\'class\'=>\'fun_get_special_permissions_fileds\']]',
        'TITLE'            => 'صلاحيات خاصة',
        'TYPE'             => 8,
        'SOURCE'           => '',
        'ATTR'             => '[\'class\'=>\'fun_get_special_permissions_fileds\']',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 4
    ],
    [
        'ID'               => 30,
        'COLUMN_NAME'      => 'ord',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(2)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'#\',\'type\'=>\'4\']',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 4
    ],
    [
        'ID'               => 31,
        'COLUMN_NAME'      => 'status',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'حالة التفعيل\',\'type\'=>\'3\']',
        'TITLE'            => 'حالة التفعيل',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 4
    ],
    [
        'ID'               => 32,
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ الإنشاء\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ الإنشاء',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 4
    ],
    [
        'ID'               => 33,
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 8,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ التعديل\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ التعديل',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 4
    ],
    [
        'ID'               => 34,
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 5
    ],
    [
        'ID'               => 35,
        'COLUMN_NAME'      => 'name',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(200)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 5
    ],
    [
        'ID'               => 36,
        'COLUMN_NAME'      => 'desc',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(200)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 5
    ],
    [
        'ID'               => 37,
        'COLUMN_NAME'      => 'type',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => '\'text\'',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'enum',
        'COLUMN_TYPE'      => 'enum(\'text\',\'checkbox\',\'textarea\',\'multi\',\'editor\',\'article\',\'list\',\'multi_list\',\'hidden\')',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'نص\',\'مربع إختيار\',\'منطقة نصوص\',\'عدة قيم متغيرة\',\'محرر نصوص\',\'مقالة من التصنيف العام\',\'قائمة منسدلة\',\'قائمة منسدلة متعددة الخيارات\',\'مخفي\']',
        'TITLE'            => '',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 5
    ],
    [
        'ID'               => 38,
        'COLUMN_NAME'      => 'value',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'text',
        'COLUMN_TYPE'      => 'text',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 5
    ],
    [
        'ID'               => 39,
        'COLUMN_NAME'      => 'status',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => '1',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 5
    ],
    [
        'ID'               => 40,
        'COLUMN_NAME'      => 'section',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => '\'site\'',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(20)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 5
    ],
    [
        'ID'               => 41,
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(10) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '[\'title\'=>\'#\',\'type\'=>\'4\']',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 6
    ],
    [
        'ID'               => 42,
        'COLUMN_NAME'      => 'name',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(500)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'اسم الجدول\',\'type\'=>\'0\']',
        'TITLE'            => 'اسم الجدول',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 6
    ],
    [
        'ID'               => 43,
        'COLUMN_NAME'      => 'title',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(500)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'عنوان الصفحة المرتبطة بالجدول\',\'type\'=>\'0\']',
        'TITLE'            => 'عنوان الصفحة المرتبطة بالجدول',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 6
    ],
    [
        'ID'               => 44,
        'COLUMN_NAME'      => 'new',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => '\'جديد\'',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(500)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'عنوان زر إضافة جديد\',\'type\'=>\'0\']',
        'TITLE'            => 'عنوان زر إضافة جديد',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 6
    ],
    [
        'ID'               => 45,
        'COLUMN_NAME'      => 'edit',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => '\'تعديل\'',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(500)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'عنوان زر تعديل\',\'type\'=>\'0\']',
        'TITLE'            => 'عنوان زر تعديل',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 6
    ],
    [
        'ID'               => 46,
        'COLUMN_NAME'      => 'status',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'عرض كقائمة\',\'type\'=>\'3\']',
        'TITLE'            => 'عرض كقائمة',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 6
    ],
    [
        'ID'               => 47,
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 8,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ الإنشاء\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ الإنشاء',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 6
    ],
    [
        'ID'               => 48,
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 9,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ التعديل\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ التعديل',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 6
    ],
    [
        'ID'               => 49,
        'COLUMN_NAME'      => 'show_add_btn',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'إظهار زر إضافة جديد\',\'type\'=>\'3\']',
        'TITLE'            => 'إظهار زر إضافة جديد',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 6
    ],
    [
        'ID'               => 50,
        'COLUMN_NAME'      => 'namespace',
        'ORDINAL_POSITION' => 8,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(500)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'المسار البرمجي للموديل\',\'type\'=>\'0\']',
        'TITLE'            => 'المسار البرمجي للموديل',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 6
    ],
    [
        'ID'               => 51,
        'COLUMN_NAME'      => 'ID',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(10) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '[\'title\'=>\'#\',\'type\'=>\'4\']',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'ID'               => 52,
        'COLUMN_NAME'      => 'COLUMN_NAME',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(64)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'اسم الحقل\',\'type\'=>\'0\']',
        'TITLE'            => 'اسم الحقل',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'ID'               => 53,
        'COLUMN_NAME'      => 'ORDINAL_POSITION',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(10)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الترتيب\',\'type\'=>\'0\']',
        'TITLE'            => 'الترتيب',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'ID'               => 54,
        'COLUMN_NAME'      => 'COLUMN_DEFAULT',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'longtext',
        'COLUMN_TYPE'      => 'longtext',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'القيمة الإفتراضية للحقل\',\'type\'=>\'0\']',
        'TITLE'            => 'القيمة الإفتراضية للحقل',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'ID'               => 55,
        'COLUMN_NAME'      => 'IS_NULLABLE',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(3)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'هل الحقل يقبل القيمة NULL\',\'type\'=>\'0\']',
        'TITLE'            => 'هل الحقل يقبل القيمة NULL',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'ID'               => 56,
        'COLUMN_NAME'      => 'DATA_TYPE',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(64)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'نوع الحقل في قاعدة البيانات\',\'type\'=>\'0\']',
        'TITLE'            => 'نوع الحقل في قاعدة البيانات',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'ID'               => 57,
        'COLUMN_NAME'      => 'COLUMN_TYPE',
        'ORDINAL_POSITION' => 8,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'longtext',
        'COLUMN_TYPE'      => 'longtext',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'نوع الحقل في قاعدة البيانات\',\'type\'=>\'0\']',
        'TITLE'            => 'نوع الحقل في قاعدة البيانات',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'ID'               => 58,
        'COLUMN_NAME'      => 'EXTRA',
        'ORDINAL_POSITION' => 9,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الخصائص الإضافية للحقل\',\'type\'=>\'0\']',
        'TITLE'            => 'الخصائص الإضافية للحقل',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'ID'               => 59,
        'COLUMN_NAME'      => 'COLUMN_COMMENT',
        'ORDINAL_POSITION' => 10,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(1024)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الترتيب\',\'type\'=>\'0\']',
        'TITLE'            => 'الترتيب',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'ID'               => 60,
        'COLUMN_NAME'      => 'TITLE',
        'ORDINAL_POSITION' => 11,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(500)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'عنوان الحقل بالعربي\',\'type\'=>\'0\']',
        'TITLE'            => 'عنوان الحقل بالعربي',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'ID'               => 61,
        'COLUMN_NAME'      => 'TYPE',
        'ORDINAL_POSITION' => 12,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(2)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'نوع الحقل عند التحرير\',\'type\'=>\'0\']',
        'TITLE'            => 'نوع الحقل عند التحرير',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'ID'               => 62,
        'COLUMN_NAME'      => 'SOURCE',
        'ORDINAL_POSITION' => 13,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(1024)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'مصدر بيانات الحقل\',\'type\'=>\'0\']',
        'TITLE'            => 'مصدر بيانات الحقل',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'ID'               => 63,
        'COLUMN_NAME'      => 'ATTR',
        'ORDINAL_POSITION' => 14,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(1024)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'خصائص الحقل\',\'type\'=>\'1\']',
        'TITLE'            => 'خصائص الحقل',
        'TYPE'             => 1,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'ID'               => 64,
        'COLUMN_NAME'      => 'STATUS',
        'ORDINAL_POSITION' => 15,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'نشر\',\'type\'=>\'3\']',
        'TITLE'            => 'نشر',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'ID'               => 65,
        'COLUMN_NAME'      => 'SHOW_IN_LIST',
        'ORDINAL_POSITION' => 16,
        'COLUMN_DEFAULT'   => '1',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'عرض الحقل كعمود في صفحة العرض\',\'type\'=>\'3\']',
        'TITLE'            => 'عرض الحقل كعمود في صفحة العرض',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'ID'               => 66,
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 17,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ الإنشاء\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ الإنشاء',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'ID'               => 67,
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 18,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ التعديل\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ التعديل',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'ID'               => 68,
        'COLUMN_NAME'      => 'TABLE_ID',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(10)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الجدول\',\'type\'=>\'0\']',
        'TITLE'            => 'الجدول',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 7
    ],
    [
        'ID'               => 69,
        'COLUMN_NAME'      => 'show_name',
        'ORDINAL_POSITION' => 12,
        'COLUMN_DEFAULT'   => '1',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'عرض اسم المستخدم قبل الوقفات\',\'type\'=>\'3\']',
        'TITLE'            => 'عرض اسم المستخدم قبل الوقفات',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 70,
        'COLUMN_NAME'      => 'api_token',
        'ORDINAL_POSITION' => 15,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(60)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'#\',\'type\'=>\'4\']',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 71,
        'COLUMN_NAME'      => 'created_by_app',
        'ORDINAL_POSITION' => 16,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تم إنشاء المستخدم بواسطة التطبيق\',\'type\'=>\'4\']',
        'TITLE'            => 'تم إنشاء المستخدم بواسطة التطبيق',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 72,
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '[\'title\'=>\'#\',\'type\'=>\'4\']',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 73,
        'COLUMN_NAME'      => 'name',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'اسم الموظف\',\'type\'=>\'0\']',
        'TITLE'            => 'اسم الموظف',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 74,
        'COLUMN_NAME'      => 'username',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(20)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'اسم المستخدم\',\'type\'=>\'0\']',
        'TITLE'            => 'اسم المستخدم',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 75,
        'COLUMN_NAME'      => 'password',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(60)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'كلمة المرور\',\'type\'=>\'0\']',
        'TITLE'            => 'كلمة المرور',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 76,
        'COLUMN_NAME'      => 'phone',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(20)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'رقم الجوال\',\'type\'=>\'0\']',
        'TITLE'            => 'رقم الجوال',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 77,
        'COLUMN_NAME'      => 'email',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(50)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'البريد الإلكتروني\',\'type\'=>\'0\']',
        'TITLE'            => 'البريد الإلكتروني',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 78,
        'COLUMN_NAME'      => 'photo',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الصورة الشخصية\',\'type\'=>\'0\',\'para\'=>[\'id\'=>\'img-upload\']]',
        'TITLE'            => 'الصورة الشخصية',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '[\'id\'=>\'img-upload\']',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 79,
        'COLUMN_NAME'      => 'job_title',
        'ORDINAL_POSITION' => 8,
        'COLUMN_DEFAULT'   => '1',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(3)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'المسمى الوظيفي\',\'type\'=>\'2\',\'para\'=>[\'source\'=>[\'function\'=>\'GetUserJobs\']]]',
        'TITLE'            => 'المسمى الوظيفي',
        'TYPE'             => 2,
        'SOURCE'           => '[\'function\'=>\'GetUserJobs\']',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 80,
        'COLUMN_NAME'      => 'status',
        'ORDINAL_POSITION' => 9,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'حالة التفعيل\',\'type\'=>\'3\']',
        'TITLE'            => 'حالة التفعيل',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 81,
        'COLUMN_NAME'      => 'permissions',
        'ORDINAL_POSITION' => 10,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(2000)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'صلاحيات إضافية\',\'type\'=>\'4\']',
        'TITLE'            => 'صلاحيات إضافية',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 82,
        'COLUMN_NAME'      => 'remember_token',
        'ORDINAL_POSITION' => 11,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(60)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'#\',\'type\'=>\'4\']',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 83,
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 12,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '[\'title\'=>\'آخر دخول\',\'type\'=>\'4\']',
        'TITLE'            => 'آخر دخول',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 84,
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 13,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ الإنشاء\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ الإنشاء',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 85,
        'COLUMN_NAME'      => 'email_verified_at',
        'ORDINAL_POSITION' => 14,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تفعيل البريد\',\'type\'=>\'4\']',
        'TITLE'            => 'تفعيل البريد',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 86,
        'COLUMN_NAME'      => 'city',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(50)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'المدينة\',\'type\'=>\'0\']',
        'TITLE'            => 'المدينة',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 87,
        'COLUMN_NAME'      => 'country',
        'ORDINAL_POSITION' => 8,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(50)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الدولة\',\'type\'=>\'0\']',
        'TITLE'            => 'الدولة',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 8
    ],
    [
        'ID'               => 88,
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 9
    ],
    [
        'ID'               => 89,
        'COLUMN_NAME'      => 'user_id',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 9
    ],
    [
        'ID'               => 90,
        'COLUMN_NAME'      => 'group_id',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '',
        'TITLE'            => '',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 9
    ],
    [
        'ID'               => 91,
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ الإنشاء\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ الإنشاء',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 9
    ],
    [
        'ID'               => 92,
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ التعديل\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ التعديل',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 9
    ],
    [
        'ID'               => 93,
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11)',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '[\'title\'=>\'#\',\'type\'=>\'4\']',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 10
    ],
    [
        'ID'               => 94,
        'COLUMN_NAME'      => 'table',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'text',
        'COLUMN_TYPE'      => 'text',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'اسم الجدول\',\'type\'=>\'5\']',
        'TITLE'            => 'اسم الجدول',
        'TYPE'             => 5,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 10
    ],
    [
        'ID'               => 95,
        'COLUMN_NAME'      => 'row_id',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'رقم السجل\/الصف\',\'type\'=>\'0\']',
        'TITLE'            => 'رقم السجل\/الصف',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 10
    ],
    [
        'ID'               => 96,
        'COLUMN_NAME'      => 'action',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'العملية\',\'type\'=>\'0\']',
        'TITLE'            => 'العملية',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 10
    ],
    [
        'ID'               => 97,
        'COLUMN_NAME'      => 'user_id',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'المستخدم\',\'type\'=>\'4\']',
        'TITLE'            => 'المستخدم',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 10
    ],
    [
        'ID'               => 98,
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ التحديث\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ التحديث',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 10
    ],
    [
        'ID'               => 99,
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ العملية\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ العملية',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 10
    ],
    [
        'ID'               => 100,
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(10) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '[\'title\'=>\'#\',\'type\'=>\'4\']',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 11
    ],
    [
        'ID'               => 101,
        'COLUMN_NAME'      => 'name',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'اسم الكونترولر\',\'type\'=>\'0\']',
        'TITLE'            => 'اسم الكونترولر',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 11
    ],
    [
        'ID'               => 102,
        'COLUMN_NAME'      => 'title',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'عنوان الكونترولر\',\'type\'=>\'0\']',
        'TITLE'            => 'عنوان الكونترولر',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 11
    ],
    [
        'ID'               => 103,
        'COLUMN_NAME'      => 'namespace',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => '\'تعديل\'',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'المجلد\\\/مساحة الاسم البرمجي\',\'type\'=>\'0\']',
        'TITLE'            => 'المجلد\/مساحة الاسم البرمجي',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 11
    ],
    [
        'ID'               => 104,
        'COLUMN_NAME'      => 'url_prefix',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => '\'تعديل\'',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'لاحقة الروابط المرتبطة بالكونترولر\',\'type\'=>\'0\']',
        'TITLE'            => 'لاحقة الروابط المرتبطة بالكونترولر',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 11
    ],
    [
        'ID'               => 105,
        'COLUMN_NAME'      => 'table_id',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(10)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الجدول المرتبط بالكنترولر\',\'type\'=>\'2\',\'para\'=>[\'source\'=>[\'function\'=>\'TablesList\']]]',
        'TITLE'            => 'الجدول المرتبط بالكنترولر',
        'TYPE'             => 2,
        'SOURCE'           => '[\'function\'=>\'TablesList\']',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 11
    ],
    [
        'ID'               => 106,
        'COLUMN_NAME'      => 'status',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الروابط الأساسية*\',\'type\'=>\'3\']',
        'TITLE'            => 'الروابط الأساسية*',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 11
    ],
    [
        'ID'               => 107,
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 8,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ الإنشاء\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ الإنشاء',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 11
    ],
    [
        'ID'               => 108,
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 9,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ التعديل\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ التعديل',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 11
    ],
    [
        'ID'               => 109,
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11)',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '[\'title\'=>\'#\',\'type\'=>\'0\']',
        'TITLE'            => '#',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 12
    ],
    [
        'ID'               => 110,
        'COLUMN_NAME'      => 'user_id',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(11)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'رقم الموظف\',\'type\'=>\'0\']',
        'TITLE'            => 'رقم الموظف',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 12
    ],
    [
        'ID'               => 111,
        'COLUMN_NAME'      => 'setting',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الإعداد\',\'type\'=>\'0\']',
        'TITLE'            => 'الإعداد',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 12
    ],
    [
        'ID'               => 112,
        'COLUMN_NAME'      => 'value',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'القيمة\',\'type\'=>\'0\']',
        'TITLE'            => 'القيمة',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 12
    ],
    [
        'ID'               => 113,
        'COLUMN_NAME'      => 'value2',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'قميمة٢\',\'type\'=>\'0\']',
        'TITLE'            => 'قميمة٢',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 12
    ],
    [
        'ID'               => 114,
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ التعديل\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ التعديل',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 12
    ],
    [
        'ID'               => 115,
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ الإنشاء\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ الإنشاء',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 12
    ],
    [
        'ID'               => 116,
        'COLUMN_NAME'      => 'id',
        'ORDINAL_POSITION' => 1,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(10) unsigned',
        'EXTRA'            => 'auto_increment',
        'COLUMN_COMMENT'   => '[\'title\'=>\'#\',\'type\'=>\'4\']',
        'TITLE'            => '#',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 13
    ],
    [
        'ID'               => 117,
        'COLUMN_NAME'      => 'type',
        'ORDINAL_POSITION' => 2,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'نوع الرابط\',\'type\'=>\'2\',\'para\'=>[\'source\'=>[\'function\'=>\'RoutesTypesList\']]]',
        'TITLE'            => 'نوع الرابط',
        'TYPE'             => 2,
        'SOURCE'           => '[\'function\'=>\'RoutesTypesList\']',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 13
    ],
    [
        'ID'               => 118,
        'COLUMN_NAME'      => 'middleware',
        'ORDINAL_POSITION' => 3,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(10)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'المصادقة\',\'type\'=>\'2\',\'para\'=>[\'source\'=>[\'function\'=>\'MiddlewareList\']]]',
        'TITLE'            => 'المصادقة',
        'TYPE'             => 2,
        'SOURCE'           => '[\'function\'=>\'MiddlewareList\']',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 13
    ],
    [
        'ID'               => 119,
        'COLUMN_NAME'      => 'controller_id',
        'ORDINAL_POSITION' => 4,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'int',
        'COLUMN_TYPE'      => 'int(10)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الكنترولر\',\'type\'=>\'2\',\'para\'=>[\'source\'=>[\'function\'=>\'ControllersList\']]]',
        'TITLE'            => 'الكنترولر',
        'TYPE'             => 2,
        'SOURCE'           => '[\'function\'=>\'ControllersList\']',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 13
    ],
    [
        'ID'               => 120,
        'COLUMN_NAME'      => 'action',
        'ORDINAL_POSITION' => 5,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(50)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الدالة للتنفيذ\',\'type\'=>\'2\',\'para\'=>[\'source\'=>[\'function\'=>\'ControllersActionsList\']]]',
        'TITLE'            => 'الدالة للتنفيذ',
        'TYPE'             => 2,
        'SOURCE'           => '[\'function\'=>\'ControllersActionsList\']',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 13
    ],
    [
        'ID'               => 121,
        'COLUMN_NAME'      => 'route',
        'ORDINAL_POSITION' => 6,
        'COLUMN_DEFAULT'   => null,
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'varchar',
        'COLUMN_TYPE'      => 'varchar(100)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'الرابط\',\'type\'=>\'0\']',
        'TITLE'            => 'الرابط',
        'TYPE'             => 0,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 13
    ],
    [
        'ID'               => 122,
        'COLUMN_NAME'      => 'id_required',
        'ORDINAL_POSITION' => 7,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'YES',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'يتطلب رقم id\',\'type\'=>\'3\']',
        'TITLE'            => 'يتطلب رقم id',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 13
    ],
    [
        'ID'               => 123,
        'COLUMN_NAME'      => 'status',
        'ORDINAL_POSITION' => 8,
        'COLUMN_DEFAULT'   => '0',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'tinyint',
        'COLUMN_TYPE'      => 'tinyint(1)',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'نشر\',\'type\'=>\'3\']',
        'TITLE'            => 'نشر',
        'TYPE'             => 3,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 13
    ],
    [
        'ID'               => 124,
        'COLUMN_NAME'      => 'created_at',
        'ORDINAL_POSITION' => 9,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => '',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ الإنشاء\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ الإنشاء',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 1,
        'TABLE_ID'         => 13
    ],
    [
        'ID'               => 125,
        'COLUMN_NAME'      => 'updated_at',
        'ORDINAL_POSITION' => 10,
        'COLUMN_DEFAULT'   => 'CURRENT_TIMESTAMP',
        'IS_NULLABLE'      => 'NO',
        'DATA_TYPE'        => 'timestamp',
        'COLUMN_TYPE'      => 'timestamp',
        'EXTRA'            => 'on update CURRENT_TIMESTAMP',
        'COLUMN_COMMENT'   => '[\'title\'=>\'تاريخ التعديل\',\'type\'=>\'4\']',
        'TITLE'            => 'تاريخ التعديل',
        'TYPE'             => 4,
        'SOURCE'           => '',
        'ATTR'             => '',
        'STATUS'           => 0,
        'SHOW_IN_LIST'     => 0,
        'TABLE_ID'         => 13
    ]];


$users = [[
        'api_token'         => 'zI1UE9EhcuqvCt3HKpBSjLiIMuxGHAU0OpTjvEsw3xL5YB6YwQYSL85Fjk35',
        'created_by_app'    => 0,
        'name'              => 'مدير النظام',
        'username'          => 'مدير النظام',
        'password'          => '$2y$10$qwOQ.DAWY2NPJNtc9biFZubktOtHB6Mr7NMxil2ZhrtBz4gcTabF.',
        'phone'             => '00967777523272',
        'email'             => 'jalmatari@gmail.com',
        'photo'             => '\/jalmatari\/img\/users\/u_1_user6-128x128-1.jpg',
        'job_title'         => 2,
        'status'            => 1,
        'permissions'       => '[]',
        'remember_token'    => 'QX5LUOOTkaDhsCYVi1NrlvMgGvvSp3HylLAMVD77idjQUCYpor4IElDQeqj1',
        'email_verified_at' => null,
        'city'              => 'الرياض',
        'country'           => 'السعودية'
    ]];


$users_groups = [[
        'user_id'  => 1,
        'group_id' => 1
    ]];


$controllers = [[
        'name'       => 'AdminController',
        'title'      => '',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Admin',
        'url_prefix' => '',
        'table_id'   => 0,
        'status'     => 0
    ],
    [
        'name'       => 'ControllersController',
        'title'      => 'الكونترولات',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Admin',
        'url_prefix' => 'controllers',
        'table_id'   => 11,
        'status'     => 1
    ],
    [
        'name'       => 'GroupsController',
        'title'      => 'مجموعات المستخدمين',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Admin',
        'url_prefix' => 'groups',
        'table_id'   => 2,
        'status'     => 1
    ],
    [
        'name'       => 'MenuController',
        'title'      => 'قوائم لوحة التحكم',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Admin',
        'url_prefix' => 'menu',
        'table_id'   => 3,
        'status'     => 1
    ],
    [
        'name'       => 'PermissionsController',
        'title'      => 'صلاحيات الموظفين',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Admin',
        'url_prefix' => 'permissions',
        'table_id'   => 4,
        'status'     => 1
    ],
    [
        'name'       => 'SettingsController',
        'title'      => 'الإعدادات',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Admin',
        'url_prefix' => 'settings',
        'table_id'   => 5,
        'status'     => 1
    ],
    [
        'name'       => 'TablesController',
        'title'      => 'جداول قاعدة البيانات',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Admin',
        'url_prefix' => 'tables',
        'table_id'   => 6,
        'status'     => 1
    ],
    [
        'name'       => 'UsersController',
        'title'      => 'بيانات الموظفين',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Admin',
        'url_prefix' => 'users',
        'table_id'   => 8,
        'status'     => 1
    ],
    [
        'name'       => 'APIController',
        'title'      => '',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Core',
        'url_prefix' => '',
        'table_id'   => 0,
        'status'     => 0
    ],
    [
        'name'       => 'AppController',
        'title'      => '',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Core',
        'url_prefix' => '',
        'table_id'   => 0,
        'status'     => 0
    ],
    [
        'name'       => 'ErrorsController',
        'title'      => 'الأخطاء البرمجية',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Core',
        'url_prefix' => 'errors',
        'table_id'   => 1,
        'status'     => 1
    ],
    [
        'name'       => 'RoutesController',
        'title'      => 'الروابط',
        'namespace'  => 'Jalmatari\\Http\\Controllers\\Admin',
        'url_prefix' => 'routes',
        'table_id'   => 13,
        'status'     => 1
    ]];


$routes = [[
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 7,
        'action'        => 'recheck',
        'route'         => 'recheck',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 7,
        'action'        => 'route',
        'route'         => 'route',
        'id_required'   => 1,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 7,
        'action'        => 'cols',
        'route'         => 'cols',
        'id_required'   => 1,
        'status'        => 1
    ],
    [
        'type'          => 1,
        'middleware'    => 'AdminAuth',
        'controller_id' => 7,
        'action'        => 'saveCols',
        'route'         => 'cols',
        'id_required'   => 1,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 7,
        'action'        => 'genController',
        'route'         => 'genController',
        'id_required'   => 1,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 7,
        'action'        => 'genMolel',
        'route'         => 'genMolel',
        'id_required'   => 1,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 7,
        'action'        => 'addTablesToMenus',
        'route'         => 'addTablesToMenus',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 8,
        'action'        => 'login_as',
        'route'         => 'login_as',
        'id_required'   => 1,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 1,
        'action'        => 'index',
        'route'         => 'admin',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 1,
        'action'        => 'index',
        'route'         => 'start',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 11,
        'action'        => 'error',
        'route'         => 'error',
        'id_required'   => 1,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 11,
        'action'        => 'delete_all',
        'route'         => 'delete_all',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 1,
        'action'        => 'unauthorized',
        'route'         => 'unauthorized',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 1,
        'action'        => 'construction',
        'route'         => 'construction',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'PublicAuth',
        'controller_id' => 1,
        'action'        => 'createSession',
        'route'         => 'admin.login',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 1,
        'action'        => 'destroySession',
        'route'         => 'admin.logout',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 1,
        'middleware'    => 'PublicAuth',
        'controller_id' => 1,
        'action'        => 'storeSession',
        'route'         => 'admin.login',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'AdminAuth',
        'controller_id' => 2,
        'action'        => 'reCheck',
        'route'         => 'reCheck',
        'id_required'   => 0,
        'status'        => 1
    ],
    [
        'type'          => 0,
        'middleware'    => 'PublicAuth',
        'controller_id' => 1,
        'action'        => 'clearCache',
        'route'         => 'clearCache',
        'id_required'   => 0,
        'status'        => 1
    ]];



dd($groups,
    $menu,
    $permissions,
    $settings,
    $tables,
    $tables_cols,
    $users,
    $users_groups,
    $controllers,
    $routes);


